home/urls.py
from django.urls import path
from . import views
from home.views import LoginView, RegisterView


urlpatterns = [
    path('',views.home_page,name='home'),

    # Aboutus
    path('about',views.about,name='about'),

    # Property
    path('all-properties',views.property_listing,name='properties'),
    path('properties-map',views.property_listing_map,name='property_listing_map'),
    path('city/<str:in_city>',views.property_list_by_city,name='property_list_by_city'),

    path('properties/<str:id>',views.property_view,name='property_view'),
    path('send-property-form',views.property_form,name='property_form'),

    path('city-guide/<str:city>',views.CityGuide,name='cityguide'),

    # Search
    path('search',views.search,name='search'),

    path('resources',views.resources,name='resources'),
    path('downloads',views.download_assets,name='download_assets'),
    # Contact
    path('contact',views.contact,name='contact'),
    path('newsletter',views.newsletter,name='newsletter'),

     # Blog

    path('blogs',views.blog,name='blogs'),
    path('blog/<int:id>',views.readblog,name='blog_view'),

    # path('login/', LoginView.as_view(), name='login'),
    # path('register/', RegisterView.as_view(), name='register'),

    path('login/', views.login, name='login'),
    path(r"login/(?P<is_new_registered>\d+)/$", views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('thankyou',views.thankyou_page,name="thankyou"),
    path('faqs',views.faqs,name='faqs'),
    path('about/team',views.teams,name='teams'),
    path('about/partners',views.partners,name='partners'),
    path('send-properties-to-map',views.SendPropertiesToMap,name='SendPropertiesToMap'),
    path('team-member/<str:name>/<int:id>',views.team_meber_view,name="team_meber_view"),
    path('get-favorited-properties',views.get_favorite_properties,name="get_favorite_properties"),
    path('profile',views.profile,name='profile'),
    path('favorited-properties',views.favorite_properties,name="favorite_properties"),
    path('exclusive-properties',views.exclusive_properties,name="exclusive_properties"),
    path('my-properties',views.my_properties,name="my_properties"),
    path('monthly-offers',views.monthly_offers,name="monthly_offers"),
    path('submit-property',views.submit_property,name='submit_property'),
    path('construction-updates',views.property_updates,name="property_updates"),
    path('construction-updates/<str:property_name>',views.construction_update_view,name='construction-updates-view'),

    # calulators
    path('stamp-duty-calculator',views.stamp_duty_calculator,name='stamp_duty_calculator'),
    path('mortgage-calculator',views.mortgage_calculator,name='mortgage_calculator'),

    path('updated-index',views.updated_index,name='updated_index'),

]

lpc/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField
from datetime import datetime
# from django.contrib.auth import get_user_model
# User = get_user_model()
from django.db.models.signals import post_save
from django.dispatch import receiver
from geopy.geocoders import Nominatim

class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)


PROP_TYPE_CHOICES =(
    ("1", "studio"),
    ("2", "apartment"),
    )

FURNITURE_TYPE_CHOICES =(
    ("1", "room"),
    ("2", "bathrooms"),
    ("3", "garage"),
    )

# CITIES_CHOICES = PropertyCities.objects.all().values_list('name', flat=True)
# CITIES_CHOICES = tuple(CITIES_CHOICES)

CITIES_CHOICES = (
    ("1", "birmingham"),
    ("2", "	bolton"),
    ("3", "leeds"),
    ("4", "manchester"),
    ("5", "liverpool"),
    ("6", "london"),
    ("7", "sheffield"),
    ("8","bradford"),
    ("9","preston"),
    ("10","nottingham")

    )


class PropertyCities(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name


class Properties(models.Model):
    is_underconstruction = models.BooleanField(default=False)
    is_exclusive = models.BooleanField(default=False)

    # Basic Information
    title = models.CharField(max_length=30)
    type = models.CharField(max_length=10,choices=PROP_TYPE_CHOICES)
    price = models.IntegerField(default=0)
    yields = models.CharField(blank=True,max_length=40)
    area = models.CharField(blank=True,max_length=40)
    deposited_price = models.IntegerField(blank=True,default=0)
    # Location
    adddress = models.CharField(max_length=50)
    city = models.CharField(max_length=20,choices = CITIES_CHOICES)

    postal_code = models.CharField(max_length=10)
    lat = models.FloatField(blank=True)
    lon = models.FloatField(blank=True)

    # Detailed Information
    content = HTMLField()

    # Media
    image = models.FileField(upload_to = 'media')
    year_built = models.CharField(max_length=10)
    embedded_link_youtube = models.CharField(max_length=100)
    pub_date = models.DateField(default=datetime.now())

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title = self.title.capitalize()
        self.adddress = self.adddress.capitalize()
        self.city = self.city.lower()
        loc = self.adddress
        geolocator = Nominatim(user_agent="my_request")
        location = geolocator.geocode(loc)
        try:
            self.lat = location.latitude
            self.lon = location.longitude
        except:
            self.lat = self.lat
            self.lon = self.lon
        try:
            self.deposited_price = int(self.area) / 100 * self.price
        except:
            pass
        return super(Properties, self).save(*args, **kwargs)


class FeatureMaster(models.Model):
    feature = models.CharField(max_length=40)
    def __str__(self):
        return str(self.feature)
    def save(self, *args, **kwargs):
        self.feature = self.feature.capitalize()
        return super(FeatureMaster, self).save(*args, **kwargs)

class PropertyTypeMaster(models.Model):
    type = models.CharField(max_length=20)
    def __str__(self):
        return str(self.type)
    
class PropertyTypeMapper(models.Model):
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    type = models.ForeignKey(PropertyTypeMaster, default=None, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.property.title)



class PropertyFeatureMapper(models.Model):
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE,related_name='features')
    feature = models.ForeignKey(FeatureMaster, default=None, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.property.title)


class FurnitureMaster(models.Model):
    furniture_counts = models.CharField(max_length=5)
    def __str__(self):
        return self.furniture_counts


class PropertyFurnitureMapper(models.Model):
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    furniture_counts = models.ForeignKey(FurnitureMaster, default=None, on_delete=models.CASCADE)
    furniture_type = models.CharField(max_length=10,choices=FURNITURE_TYPE_CHOICES)
    def __str__(self):
        return str(self.property.title)


class StatusMaster(models.Model):
    status = models.CharField(max_length=20)
    def __str__(self):
        return self.status
    def save(self, *args, **kwargs):
        self.status = self.status.capitalize()
        return super(StatusMaster, self).save(*args, **kwargs)


class PropertyStatusMapper(models.Model):
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    status = models.ForeignKey(StatusMaster, default=None, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.property.title)


class UserFavProperties(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    is_checked = models.BooleanField(default=False)
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    def __str__(self):
        return f"{str(self.user)} + {self.property.title}"


class UserExclusiveProperties(models.Model):
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    def __str__(self):
        return f"{str(self.user)} + {self.property.title}"

    def save(self, *args, **kwargs):
        property = Properties.objects.get(id = self.property.id)
        property.is_underconstruction = True
        property.is_exclusive=True
        property.save()
        return super(UserExclusiveProperties, self).save(*args, **kwargs)


class Discount(models.Model):
    value = models.IntegerField(default=0, verbose_name="Value")
    is_percentage = models.BooleanField(default=False, verbose_name="Is percentage?")
    def __str__(self):
        if self.is_percentage:
            return "{0}% - Discount".format(self.value)
        return "${0} - Discount".format(self.value)

    class Meta:
        verbose_name = "Discount"
        verbose_name_plural = "Discounts"


class PropertyOffers(models.Model):
    title = models.CharField(max_length=100)
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    # user = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    is_automaically = models.BooleanField(default=False)
    discount =  models.ForeignKey('Discount', on_delete=models.CASCADE)

    def __str__(self):
        return (str(self.title))



class PropertyImage(models.Model):
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'media')
    def __str__(self):
        return self.property.title

from django_resized import ResizedImageField

class DownloadableAssets(models.Model):
    title = models.CharField(max_length=30)
    image = ResizedImageField(size=[300, 180], upload_to = 'media/download_assets')
    desc = models.TextField(default = " ",blank=True)
    downloadable_url = models.URLField(max_length=200)

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     self.feature = self.title.capitalize()

    #     # # image = Image.open(self.image.path)
    #     # self.image = self.image.resize()
    #     size = (300, 180)
    #     filename = self.image
    #     image = Image.open(filename)
    #     image.thumbnail(size, Image.ANTIALIAS)
    #     image.save(filename)
    #     # self.image= image
    #     return super(DownloadableAssets, self).save(*args, **kwargs)


class ConstructionUpdates(models.Model):
    property = models.ForeignKey(Properties, default=None, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    desc = models.TextField(default = " ",blank=True)
    pub_date = models.DateField(default=datetime.now())

    def __str__(self):
        return self.title


class ConstructionUpdatesImage(models.Model):
    property_update_id = models.ForeignKey(ConstructionUpdates, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'media/property_updates')
    def __str__(self):
        return self.property_update_id.title



class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    fname = models.CharField(max_length=20, blank=True)
    lname = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=20, blank=True)
    mobile = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=20, blank=True)
    def __str__(self):
        return self.fname

# Signals used to create profile instance
@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance,
        fname=instance.first_name,lname=instance.last_name,email=instance.email)

@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.profile.save()
    except:
        pass


class TeamMembers(models.Model):
    image = models.FileField(upload_to = 'media/team')
    name = models.CharField(max_length=30, blank=True)
    role = models.CharField(max_length=30, blank=True)
    desc = models.TextField(default="")
    mobile = models.CharField(max_length=15, blank=True)
    email = models.CharField(max_length=40, blank=True)
    address = models.CharField(max_length=50, blank=True)
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.capitalize()
        return super(TeamMembers, self).save(*args, **kwargs)
    
    
    

class Blogs(models.Model):

home/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email / Username')

home/templates/user/dashboard/construction_update.html
{% extends 'user/basic.html' %} {% load static %} {% block title %}Property
Updates{{page_data.page_name}}{% endblock title%} {% block css %} {% endblock css %} {% block body %}

<!-- Sub banner start -->
<div class="sub-banner">
    <div class="container">
        <div class="breadcrumb-area">
            <h1>Property Updates</h1>
            <ul class="breadcrumbs">
                <li><a href="/">Home</a></li>
                <li class="active">Property Updates</li>
            </ul>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<div class="properties-details-page content-area">
    <div class="container">

        <div class="main-title">
            <h1>
                Keep On Track
                </h1>
            <p>As off-plan development experts, we complete all due diligence and soliciting before our developments complete construction. Most of our properties are completed on time. Here are all of our developments that are currently under construction.</p>
          </div>
        <div class="row">
            {%for property in construction_updates %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="container property-box-6 w-80">
                    <a href="/construction-updates/{{property.property.title}}">
                        <div class="property-photo">
                            <img src="/media/{{property.property.image}}" alt="photo" class="img-fluid w-100"  style="height:400px;;"/>
                        </div>
                        <div class="tag">Under Construction</div>
                    </a>
                    <div class="property-inner">
                        <div class="property-info">
                            <h4 class="properties-name">
                                <a href="/construction-updates/{{property.property.title}}">{{property.property.title}}</a>
                            </h4>
                            <p class="location">
                                <a href="/construction-updates/{{property.property.title}}">
                                    <i class="fa fa-map-marker"></i> {{property.property.get_city_display}}
                                </a>
                        </div>
                    </div>
                    <div class="team-hover-content">
                        <a href="/construction-updates/{{property.property.title}}">
                            <div class="property-photo">
                                <img src="/media/{{property.property.image}}" alt="photo" class="img-fluid w-100"style="height:400px;" />
                            </div>
                        </a>
                        <div class="property-info mt-0">
                            <h4 class="properties-name">
                                <a href="/construction-updates/{{property.property.title}}">{{property.property.title}}</a>
                            </h4>
                            <p class="location">
                                <a href="/construction-updates/{{property.property.title}}">
                                    <i class="fa fa-map-marker"></i> {{property.property.get_city_display}}
                                </a>
                            </p>
                        </div>

                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>

    {%endblock body%}

home/templates/user/dashboard/construction_update_view.html
{% extends 'user/basic.html' %} {% load static %} {% block title %}{{page_data.page_name}}{{page_data.page_name}}{% endblock title%} {% block css %} {% endblock css %} {% block body %}

<!-- Sub banner start -->
<div class="sub-banner">
  <div class="container">
    <div class="breadcrumb-area">
      <h1>          Construction Updates
      </h1>
      <ul class="breadcrumbs">
        <li><a href="/">Home</a></li>
        <li class="active">
          Construction Updates
          </li>
      </ul>
    </div>
  </div>
</div>
<!-- Sub Banner end -->

<!-- Services start -->

<div class="properties-details-page content-area">
  <div class="container">
    <div class="inside-properties">
      <div class="main-title">
        <h1>
          Construction Updates | <span style="color:#00CE8D;">{{page_data.page_name}}</span>
          </h1>
      </div>
      <iframe
        src="https://www.youtube.com/embed/5e0LxrLSzok"
        allowfullscreen=""
      ></iframe>
    </div>
  </div>

  <div class="services content-area content-area-12">
    {%for construction in constructions_lst %}
      <!-- Main title -->
      <div class="main-title">
        <h4>{{construction.title }} <span style="color:#00CE8D;">Construction Update – {{construction.pub_date}}</span>
        </h4>
        <p>

          {{construction.title | title }} is progressing well, with the completion date nearing.

        </p>
      </div>

      <div class="slick-slider-area ">
        <div
          class="row slick-carousel"
          data-slick='{"slidesToShow": 3, "responsive":[{"breakpoint": 1024,"settings":{"slidesToShow": 2}}, {"breakpoint": 768,"settings":{"slidesToShow": 1}}]}'>
          {%for img in construction.images %}
          <div class="slick-slide-item p-0">
            <div class="card service-box p-0">
              <img
                class="card-img-top"
                src="/media/{{img.images}}"
                style="height: 300px"
                alt="service"
                onclick="zoom()"
              />
            </div>
          </div>
          {%endfor%}


        </div>
        <div class="slick-btn mb-5">
          <div class="slick-prev slick-arrow-buton-2 sab-4">
            <i class="fa fa-angle-left"></i>
          </div>
          <div class="slick-next slick-arrow-buton-2 sab-3">
            <i class="fa fa-angle-right"></i>
          </div>
        </div>
      </div>
      <br>

  </div>

  <!-- Modal Slider Start -->
<div id="myModal" class="modale">
  <span class="close">&times;</span>

    <div id="carouselInterval" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        {% for img in construction.images %}
          {% if forloop.first %}
            <div class="carousel-item active p-5" >

              <img src="/media/{{img.images}}" class="d-block img-fluid mx-auto zoom-images" alt="slider-photo"
             onclick="zoom(event)"/>

            </div>
          {%else%}
            <div class="carousel-item p-5">

              <img src="/media/{{img.images}}" class="d-block img-fluid mx-auto zoom-images" alt="slider-photo"  onclick="zoom(event)"/>
            </div>
          {%endif%}

        {%endfor%}
      </div>
      <button class="carousel-control-prev prevv" type="button" data-bs-target="#carouselInterval" data-bs-slide="prev">
        <!-- <span class="carousel-control-prev-icon" aria-hidden="true"></span> -->
        <i class="fa fa-angle-left"></i>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next nextt" type="button" data-bs-target="#carouselInterval" data-bs-slide="next">
        <i class="fa fa-angle-right"></i>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
</div>
{%endfor%}
<!-- Modal Slider End -->


  <!-- Services end -->

<script type="text/javascript">
  var $ = jQuery.noConflict();

  $(document).ready(function(){

  var zoomImages = $('.zoom-images');

  zoomImages.each(function() {
          $(this).imageZoom();
    });
  });
</script>

<script>
  function zoom(){

    document.getElementById('myModal').style.display="block";
  }

  var span = document.getElementsByClassName("close")[0];
  span.onclick = function() {
    console.log("sada");
  document.getElementById('myModal').style.display = "none";
  }
</script>

  {%endblock body%}
</div>

home/templates/user/dashboard/discounted_properties.html
{% extends './basic.html' %} 
 {% block title %} Monthly Offers {{page_data.page_name}}{% endblock title%} 
 {% block body %}

 <div class="dashboard-content">
    <div class="dashboard-list">
        <div class="container ml-5">
            <h3 class="heading m-3">Monthly Offers</h3>

            {%if page_data.not_found%}
            <div class="pages-404">
            <div class="nobottomborder">
              <h1 style='color:#00CE8D'>
                It seems we can't find what you're looking for.!</h1>
              <div class="row">
                <div class="col-lg-5 col-md-5">
                  <div class="coming-form clearfix" style="margin-top:0px;">
                          <p>Please try searching again</p>
                          
                      </div>
                  </div>
              </div>
          </div>
        </div>
    {%endif%}
            <div id="list_view_div">
                {%for property in properties %}
                <!-- Property box 2 start -->
                <div class="property-box-2">
                    <div class="row g-0">
                        <div class="col-lg-5 col-md-5">
                            <div class="property-photo">
                                <a href="/properties/{{property.id}}" class="property-img">
                                    <img src="/media/{{property.image}}" alt="properties"
                                        class="img-fluid" />
                                    <div class="listing-badges">
                                        <div class="tag">{{property.offer}}% off</div>
                                    </div>
                                    <div class="price-box">
                                        From   <span class="cut">{{property.discounted_price}}</span>
                                    </span>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-7 col-md-7">
                            <div class="detail">
                                <div class="hdg">
                                    <h3 class="title">
                                        <a href="/properties/{{property.id}}">{{property.title}}</a>
                                    </h3>
                                    <h5 class="location">
                                        <a href="/properties/{{property.id}}">
                                            <i class="flaticon-pin"></i>{{property.adddress}}
                                        </a>
                                    </h5>
                                </div>
                                <ul class="facilities-list clearfix">
                                    <li><span>Area</span>{{property.area}} Sqft</li>
                                    <li><span>Bedrooms</span> {{property.room}}</li>
                                    <li><span>Baths</span> {{property.bathrooms}}</li>
                                </ul>
                                <div class="footer">
                                    {% if property.is_favorite %}
                                    <i class="heart fa fa-heart" id="{{property.id}}"></i>
                                    {%else%}
                                    <i class="heart fa fa-heart-o" id="{{property.id}}"></i>
                                    {%endif%}
                                    <span>
                                        <i class="flaticon-calendar"></i>{{property.pub_date}}
                                        Ago</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
 {% endblock body %}

home/templates/user/dashboard/exclusive_properties.html
{% extends './basic.html' %} 
{% block title %} Exclusive Properties {{page_data.page_name}}{% endblock title%} 
{% block body %}

<div class="dashboard-content">
    <div class="dashboard-list">
        <div class="container ml-5">
            <h3 class="heading m-3">Exclusive Properties List</h3>

            {%if page_data.not_found%}
            <div class="pages-404">
            <div class="nobottomborder">
              <h1 style='color:#00CE8D'>
                It seems we can't find what you're looking for.!</h1>
              <div class="row">
                <div class="col-lg-5 col-md-5">
                  <div class="coming-form clearfix" style="margin-top:0px;">
                          <p>Please try searching again</p>
                          
                      </div>
                  </div>
              </div>
          </div>
        </div>
    {%endif%}

    
            <div id="list_view_div">
                {%for property in exclusive_properties %}
                <!-- Property box 2 start -->
                <div class="property-box-2">
                    <div class="row g-0">
                        <div class="col-lg-5 col-md-5">
                            <div class="property-photo">
                                <a href="/properties/{{property.id}}" class="property-img">
                                    <img src="/media/{{property.image}}" alt="properties"
                                        class="img-fluid" />
                                    <div class="listing-badges">
                                        <div class="tag">{{property.status}}</div>
                                    </div>
                                    <div class="price-box">
                                        From <span>£{{property.price}}</span>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-7 col-md-7">
                            <div class="detail">
                                <div class="hdg">
                                    <h3 class="title">
                                        <a href="/properties/{{property.id}}">{{property.title}}</a>
                                    </h3>
                                    <h5 class="location">
                                        <a href="/properties/{{property.id}}">
                                            <i class="flaticon-pin"></i>{{property.adddress}}
                                        </a>
                                    </h5>
                                </div>
                                <ul class="facilities-list clearfix">
                                    <li><span>Area</span>1200 Sqft</li>
                                    <li><span>Bedrooms</span> {{property.room}}</li>
                                    <li><span>Baths</span> {{property.bathrooms}}</li>
                                </ul>
                                <div class="footer">
                                    {% if property.is_favorite %}
                                    <i class="heart fa fa-heart" id="{{property.id}}"></i>
                                    {%else%}
                                    <i class="heart fa fa-heart-o" id="{{property.id}}"></i>
                                    {%endif%}
                                    <span>
                                        <i class="flaticon-calendar"></i>{{property.pub_date}}
                                        Ago</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock body %}

home/templates/user/dashboard/newsletter.html
{% extends './basic.html' %} 
{% block title %} NEWSLETTER {{page_data.page_name}}{% endblock title%} 
{% block body %}
<div class="dashboard-content">
  <div class="pipedriveWebForms" data-pd-webforms=https://webforms.pipedrive.com/f/63kyPn6jtfojIZInYIqoI6MMRUVO8R2E4NCtovcOl80rvOIWaZvwLP64ds6ldX4rfR><script src=https://webforms.pipedrive.com/f/loader></script></div>
</div>
{% endblock body %}